### ISSUE TITLE
Update email

### ISSUE THREAD

**Issue by ux-git** [sws2apps/organized-about#141]
@mrtavor can you please change the support-sws2apps@gmail.com to the support@organized-app.com?

<img width="597" alt="Screenshot 2024-11-16 at 23 39 32" src="https://github.com/user-attachments/assets/46617d67-6d79-477a-a88f-b611bb01d4d4">

**Comment by mrtavor** [comment]
👌

**Comment by mrtavor** [comment]
Now it's done 👍
