### ISSUE TITLE
Add development roadmap link

### ISSUE THREAD

**Issue by ux-git** [sws2apps/organized-about#162]
@mrtavor could you please add to the footer the [Development roadmap](https://github.com/sws2apps/organized-app/discussions/178) link? Of course, with adding the tr_key to the Crowdin.

<img width="970" alt="Screenshot 2024-12-17 at 21 34 09" src="https://github.com/user-attachments/assets/1ad92462-8adb-47e5-bdc4-024752ca3f45" />

**Comment by mrtavor** [comment]
Okay 👍
